### ISSUE TITLE
[SECURITY] Be careful with your secrets!

### ISSUE THREAD

**Issue by SalOrak** [bennjii/ben-white#1]
Hi Ben, I'm a security research.

You may have leaked you github Access token in the .env file.
https://github.com/bennjii/ben-white/blob/master/portfolio/.env

Please make sure to include the .env file in the .gitignore.
Revoke the token as soon as possible.

And don't worry, I've leaked many more secrets :)

Hope everything is going great,

PS: Keep it up with the good work !

**Comment by bennjii** [comment]
Thanks, GitHub caught it as soon as it was committed, and has been revoked- but I appreciate the heads up! I’ve since learnt my lesson 😆
